spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${POSTGRE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_URI}
      port: 6379
      password: ${REDIS_PW}
      database: 7
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL_ACCOUNT}
    password: ${GOOGLE_EMAIL_PW}
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000 #1초
      mail.starttls.enable: true
      mail.smtp.auth: true

Jwt:
  secret: ${JWT_SECRET_KEY}
  token:
    access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}