spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${POSTGRE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      url: redis://default:Skala25a!23$@redis-1-master.redis:6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL_ACCOUNT}
    password: ${GOOGLE_EMAIL_PW}
    properties:
      mail.smtp.debug: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 1000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

Jwt:
  secret: ${JWT_SECRET_KEY}
  token:
    access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG