spring:
  profiles:
    active: local  # 로컬 실행 시엔 local, 배포 시엔 prod

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/nav7db
    username: nav7
    password: nav71234
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://nav7:nav71234@localhost:27017/navmongodb
    redis:
      host: localhost
      port: 6379
      database: 0

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${POSTGRE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_URI}
      port: 6379
      password: ${REDIS_PW}
      database: 7