apiVersion: apps/v1
kind: Deployment
metadata:
  name: nav7-backend
  namespace: sk-team-07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nav7-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
      labels:
        app: nav7-backend
    spec:
      containers:
        - name: nav7-be
          image: amdp-registry.skala-ai.com/skala25a/sk-nav7-be:1.0.0-59-fa86088462dd
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: POSTGRE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: DB_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: MONGO_URI
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: REDIS_PASSWORD
            - name: SPRING_DATA_REDIS_USERNAME
              value: "default"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: JWT_SECRET_KEY
            - name: JWT_ACCESS_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: JWT_ACCESS_EXPIRATION_TIME
            - name: JWT_REFRESH_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: JWT_REFRESH_EXPIRATION_TIME
            - name: GOOGLE_EMAIL_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: GOOGLE_EMAIL_ACCOUNT
            - name: GOOGLE_EMAIL_PW
              valueFrom:
                secretKeyRef:
                  name: nav-be-secret
                  key: GOOGLE_EMAIL_PW